on:
  workflow_dispatch:
  schedule:
    - cron: '40 3 * * *'
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name 'dciancu'
          git config user.email 'dciancu@users.noreply.github.com'
          git branch download
          git checkout download
          bash download.sh
          git commit -m 'update lists'
          git push --force -u origin download
